name: 'travaux'
version: '1.0.0'
config-version: 2

profile: 'travaux'

source-paths: ["sources", "models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets: 
    - "target"
    - "dbt_modules"

models:
  +materialized: view
  travaux:
    staging:
      +schema: staging
    marts:
      +schema: marts
