name: 'travaux'
version: '1.0.0'
config-version: 2

profile: 'travaux'

source-paths: ["sources", "models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

vars:
  min_date: '2001-01-01'
  max_date: '2051-01-01'

models:
    travaux:
      +materialized: view
      staging:
        +schema: staging
      marts:
        +schema: marts
